### ISSUE TITLE
Búsqueda de producto: filtro por título no funciona en todas las fechas

### ISSUE THREAD

**Issue by JuliaLima** [AdrianDeLasSierras/Turisticos#1]
Al realizar búsqueda de un determinado producto (campo de búsqueda por título), solo devuelve los resultados de la fecha actual, no los de todas las fechas en el que el producto se encuentra.

**Comment by augusto-altman** [comment]
Fixed with [commit](https://github.com/AdrianDeLasSierras/Turisticos/commit/ef725dd91ff2be7e13a519b3dcf8de8d53a5090d)
