### ISSUE TITLE
No puedo acceder a la descripcion e instrucciones de un producto desde la UI de busqueda

### ISSUE THREAD

**Issue by augusto-altman** [AdrianDeLasSierras/Turisticos#4]
Un vendedor no puede acceder a informacion basica de un producto facilmente desde la UI de busqueda de productos.

**Comment by JuliaLima** [comment]
resuelto en [commit](https://github.com/AdrianDeLasSierras/Turisticos/commit/8e8f4faa366f5cb1ac18d94ad60cbd185f08ee75)
