### ISSUE TITLE
No esta especificada la UI para emitir una adquisition

### ISSUE THREAD

**Issue by augusto-altman** [AdrianDeLasSierras/Turisticos#6]
No encuentro por ningun lado el prototipo para poder emitir adquisitions (y vouchers) desde el boton "comprar" en la UI de buscar productos

**Comment by JuliaLima** [comment]
resuelto en [commit](https://github.com/AdrianDeLasSierras/Turisticos/commit/7748f56cc3d3c910e0a8871c962ae6c546a267e8)
