### ISSUE TITLE
IE: Hay problemas con las fechas y horas

### ISSUE THREAD

**Issue by JuliaLima** [AdrianDeLasSierras/Turisticos#7]
Los inputs de date y time no funcionan como en otros browsers. En UI de búsqueda de productos muestra como NaN las fechas y las horas no las muestra. Genera problemas a la hora de buscar productos por fecha

**Comment by JuliaLima** [comment]
En Firefox sucede lo mismo

**Comment by augusto-altman** [comment]
Fixed on [commit](https://github.com/AdrianDeLasSierras/Turisticos/commit/17fb42c448b48e55aed5ec17e01e8e732c107366)
